"""
CivicBridge — Central Government schemes catalogue (browse/discover list).

Important, please read before extending this file:

There is no single official machine-readable master list of all ~700-1,400+
Government of India schemes. The Government's own aggregator, myScheme
(myscheme.gov.in), does not publish a documented public API for its full
catalogue (see scheme_api.py), and independent trackers openly note that no
single authoritative master list exists either.

Given that, this file is a curated, hand-checked catalogue of well-known,
real, currently/recently active Central Sector and Centrally Sponsored
Schemes, grouped by sector and implementing ministry, for USERS TO BROWSE
AND VERIFY — it intentionally does NOT attach fabricated eligibility rules,
invented benefit amounts, or guessed deep-link URLs to each entry. Where a
specific, confidently-known official domain exists it is used; otherwise the
entry points to the relevant ministry/department home page or to the
National Scholarship Portal / myScheme so the person can search for the
current, authoritative page themselves.

This list is large (150+ real schemes) but is NOT exhaustive — it cannot
responsibly be, for the reasons above. For a genuinely complete, always
current catalogue, wire scheme_api.py's SCHEME_API_URL / DATA_GOV_API_KEY
settings to an official data source you have access to (e.g. a data.gov.in
resource ID for Central Government schemes) — sync_api_schemes() will then
pull real records automatically and they will appear in /schemes alongside
this static list.

Every scheme in CivicBridge (this catalogue and benefits_data.py) is
Central Government only — CivicBridge no longer offers a state-scheme mode.
"""

CENTRAL_SCHEMES_CATALOGUE = [
    # ---------------- Agriculture, Farmers & Allied ----------------
    {"id": "pmfby", "name": "Pradhan Mantri Fasal Bima Yojana (PMFBY)", "ministry": "Ministry of Agriculture & Farmers Welfare", "category": "Agriculture", "description": "Crop insurance scheme covering losses from natural calamities, pests and diseases for enrolled farmers.", "official_url": "https://pmfby.gov.in/"},
    {"id": "kcc", "name": "Kisan Credit Card (KCC) Scheme", "ministry": "Ministry of Agriculture & Farmers Welfare", "category": "Agriculture", "description": "Provides farmers with timely, affordable short-term credit for cultivation and allied needs.", "official_url": "https://www.myscheme.gov.in/"},
    {"id": "rkvy", "name": "Rashtriya Krishi Vikas Yojana (RKVY)", "ministry": "Ministry of Agriculture & Farmers Welfare", "category": "Agriculture", "description": "Umbrella scheme supporting state-led agriculture and allied-sector development projects.", "official_url": "https://rkvy.nic.in/"},
    {"id": "pmksy", "name": "Pradhan Mantri Krishi Sinchayee Yojana (PMKSY)", "ministry": "Ministry of Agriculture & Farmers Welfare / Jal Shakti", "category": "Agriculture", "description": "\"Har Khet Ko Pani\" — expands assured irrigation and improves on-farm water use efficiency.", "official_url": "https://pmksy.gov.in/"},
    {"id": "soil-health-card", "name": "Soil Health Card Scheme", "ministry": "Ministry of Agriculture & Farmers Welfare", "category": "Agriculture", "description": "Issues farmers soil-nutrient status cards with crop-wise fertiliser and amendment recommendations.", "official_url": "https://soilhealth.dac.gov.in/"},
    {"id": "pkvy", "name": "Paramparagat Krishi Vikas Yojana (PKVY)", "ministry": "Ministry of Agriculture & Farmers Welfare", "category": "Agriculture", "description": "Promotes cluster-based organic farming among groups of farmers.", "official_url": "https://pgsindia-ncof.gov.in/"},
    {"id": "e-nam", "name": "e-NAM (National Agriculture Market)", "ministry": "Ministry of Agriculture & Farmers Welfare", "category": "Agriculture", "description": "Pan-India electronic trading portal networking APMC mandis into a unified national market.", "official_url": "https://enam.gov.in/"},
    {"id": "aif", "name": "Agriculture Infrastructure Fund (AIF)", "ministry": "Ministry of Agriculture & Farmers Welfare", "category": "Agriculture", "description": "Medium/long-term debt financing for post-harvest management and community farming infrastructure.", "official_url": "https://agriinfra.dac.gov.in/"},
    {"id": "fpo-scheme", "name": "Formation & Promotion of 10,000 FPOs Scheme", "ministry": "Ministry of Agriculture & Farmers Welfare", "category": "Agriculture", "description": "Supports formation and support of Farmer Producer Organisations.", "official_url": "https://sfacindia.com/"},
    {"id": "rashtriya-gokul-mission", "name": "Rashtriya Gokul Mission", "ministry": "Ministry of Fisheries, Animal Husbandry & Dairying", "category": "Agriculture", "description": "Conservation and development of indigenous bovine breeds and productivity enhancement.", "official_url": "https://dahd.nic.in/"},
    {"id": "ded-scheme", "name": "Dairy Entrepreneurship Development Scheme (DEDS)", "ministry": "Ministry of Fisheries, Animal Husbandry & Dairying", "category": "Agriculture", "description": "Credit-linked subsidy to set up small dairy farms and related infrastructure.", "official_url": "https://dahd.nic.in/"},
    {"id": "pmmsy", "name": "Pradhan Mantri Matsya Sampada Yojana (PMMSY)", "ministry": "Ministry of Fisheries, Animal Husbandry & Dairying", "category": "Agriculture", "description": "Flagship scheme for sustainable development of the fisheries sector (\"Blue Revolution\" successor).", "official_url": "https://pmmsy.dof.gov.in/"},
    {"id": "smam", "name": "Sub-Mission on Agricultural Mechanization (SMAM)", "ministry": "Ministry of Agriculture & Farmers Welfare", "category": "Agriculture", "description": "Subsidy support for farm machinery and custom hiring centres.", "official_url": "https://agrimachinery.nic.in/"},
    {"id": "nfsm", "name": "National Food Security Mission (NFSM)", "ministry": "Ministry of Agriculture & Farmers Welfare", "category": "Agriculture", "description": "Aims to increase production of rice, wheat, pulses, coarse cereals and commercial crops.", "official_url": "https://nfsm.gov.in/"},
    {"id": "midh", "name": "Mission for Integrated Development of Horticulture (MIDH)", "ministry": "Ministry of Agriculture & Farmers Welfare", "category": "Agriculture", "description": "Holistic support for the horticulture sector, from production to marketing.", "official_url": "https://midh.gov.in/"},
    {"id": "miss", "name": "Modified Interest Subvention Scheme (MISS)", "ministry": "Ministry of Agriculture & Farmers Welfare", "category": "Agriculture", "description": "Interest subvention on short-term crop loans for farmers who repay on time.", "official_url": "https://www.myscheme.gov.in/"},
    {"id": "kisan-rail", "name": "Kisan Rail Scheme", "ministry": "Ministry of Railways / Agriculture", "category": "Agriculture", "description": "Dedicated rail freight movement for perishable agricultural produce.", "official_url": "https://indianrailways.gov.in/"},

    # ---------------- Health & Family Welfare ----------------
    {"id": "ab-hwc", "name": "Ayushman Bharat — Ayushman Arogya Mandirs (Health & Wellness Centres)", "ministry": "Ministry of Health & Family Welfare", "category": "Health", "description": "Upgrades primary health infrastructure to deliver comprehensive primary healthcare.", "official_url": "https://ab-hwc.nhp.gov.in/"},
    {"id": "abdm", "name": "Ayushman Bharat Digital Mission (ABDM)", "ministry": "Ministry of Health & Family Welfare", "category": "Health", "description": "Builds digital health ID and interoperable digital health records infrastructure.", "official_url": "https://abdm.gov.in/"},
    {"id": "jsy", "name": "Janani Suraksha Yojana (JSY)", "ministry": "Ministry of Health & Family Welfare", "category": "Health", "description": "Cash assistance to promote institutional delivery among pregnant women.", "official_url": "https://nhm.gov.in/"},
    {"id": "jssk", "name": "Janani Shishu Suraksha Karyakaram (JSSK)", "ministry": "Ministry of Health & Family Welfare", "category": "Health", "description": "Free delivery services including caesarean section, drugs, diagnostics and transport.", "official_url": "https://nhm.gov.in/"},
    {"id": "pmsma", "name": "Pradhan Mantri Surakshit Matritva Abhiyan (PMSMA)", "ministry": "Ministry of Health & Family Welfare", "category": "Health", "description": "Free, assured antenatal checkups on a fixed date every month for pregnant women.", "official_url": "https://pmsma.nhp.gov.in/"},
    {"id": "rbsk", "name": "Rashtriya Bal Swasthya Karyakram (RBSK)", "ministry": "Ministry of Health & Family Welfare", "category": "Health", "description": "Child health screening and early intervention services for defects, deficiencies and disabilities.", "official_url": "https://nhm.gov.in/"},
    {"id": "nhm", "name": "National Health Mission (NHM)", "ministry": "Ministry of Health & Family Welfare", "category": "Health", "description": "Umbrella mission strengthening rural and urban public health systems.", "official_url": "https://nhm.gov.in/"},
    {"id": "ntep", "name": "National TB Elimination Programme (NTEP)", "ministry": "Ministry of Health & Family Welfare", "category": "Health", "description": "Free diagnosis, treatment and nutritional support (Ni-kshay Poshan Yojana) for TB patients.", "official_url": "https://tbcindia.gov.in/"},
    {"id": "mission-indradhanush", "name": "Mission Indradhanush", "ministry": "Ministry of Health & Family Welfare", "category": "Health", "description": "Immunisation drive to cover unvaccinated and partially vaccinated children and pregnant women.", "official_url": "https://nhm.gov.in/"},
    {"id": "pmjay-official-app", "name": "Pradhan Mantri Jan Aushadhi Pariyojana (PMJAP)", "ministry": "Ministry of Chemicals & Fertilizers", "category": "Health", "description": "Sells quality generic medicines at affordable prices through Jan Aushadhi Kendras.", "official_url": "https://janaushadhi.gov.in/"},
    {"id": "pmssy", "name": "Pradhan Mantri Swasthya Suraksha Yojana (PMSSY)", "ministry": "Ministry of Health & Family Welfare", "category": "Health", "description": "Sets up AIIMS-like institutions and upgrades government medical colleges.", "official_url": "https://mohfw.gov.in/"},
    {"id": "poshan-abhiyan", "name": "POSHAN Abhiyan / Saksham Anganwadi & Poshan 2.0", "ministry": "Ministry of Women & Child Development", "category": "Health", "description": "National nutrition mission targeting stunting, undernutrition and anaemia.", "official_url": "https://poshantracker.in/"},
    {"id": "npcdcs", "name": "National Programme for Prevention & Control of NCDs (NP-NCD)", "ministry": "Ministry of Health & Family Welfare", "category": "Health", "description": "Screening and management support for cancer, diabetes, cardiovascular disease and stroke.", "official_url": "https://nhm.gov.in/"},

    # ---------------- Education & Skill Development ----------------
    {"id": "samagra-shiksha", "name": "Samagra Shiksha Abhiyan", "ministry": "Ministry of Education", "category": "Education", "description": "Integrated school-education scheme covering pre-school to senior secondary level.", "official_url": "https://samagra.education.gov.in/"},
    {"id": "pm-poshan", "name": "PM POSHAN (erstwhile Mid-Day Meal Scheme)", "ministry": "Ministry of Education", "category": "Education", "description": "Hot cooked mid-day meals for children in government and government-aided schools.", "official_url": "https://pmposhan.education.gov.in/"},
    {"id": "nmmss", "name": "National Means-cum-Merit Scholarship Scheme (NMMSS)", "ministry": "Ministry of Education", "category": "Education", "description": "Scholarship for meritorious students from economically weaker sections to reduce dropout at Class VIII.", "official_url": "https://scholarships.gov.in/"},
    {"id": "post-matric-sc", "name": "Post-Matric Scholarship for SC Students", "ministry": "Ministry of Social Justice & Empowerment", "category": "Education", "description": "Financial assistance for SC students studying at post-matriculation/post-secondary stage.", "official_url": "https://scholarships.gov.in/"},
    {"id": "post-matric-st", "name": "Post-Matric Scholarship for ST Students", "ministry": "Ministry of Tribal Affairs", "category": "Education", "description": "Financial assistance for ST students studying at post-matriculation/post-secondary stage.", "official_url": "https://scholarships.gov.in/"},
    {"id": "post-matric-obc", "name": "Post-Matric Scholarship for OBC Students", "ministry": "Ministry of Social Justice & Empowerment", "category": "Education", "description": "Financial assistance for OBC students studying at post-matriculation/post-secondary stage.", "official_url": "https://scholarships.gov.in/"},
    {"id": "pre-matric-minorities", "name": "Pre-Matric Scholarship for Minorities", "ministry": "Ministry of Minority Affairs", "category": "Education", "description": "Scholarship for minority-community students in Classes 1–10.", "official_url": "https://scholarships.gov.in/"},
    {"id": "post-matric-minorities", "name": "Post-Matric Scholarship for Minorities", "ministry": "Ministry of Minority Affairs", "category": "Education", "description": "Scholarship for minority-community students beyond matriculation.", "official_url": "https://scholarships.gov.in/"},
    {"id": "top-class-sc", "name": "Top Class Education Scheme for SC Students", "ministry": "Ministry of Social Justice & Empowerment", "category": "Education", "description": "Full financial support for SC students admitted to notified premier institutions.", "official_url": "https://scholarships.gov.in/"},
    {"id": "national-fellowship-sc", "name": "National Fellowship for SC Students", "ministry": "Ministry of Social Justice & Empowerment", "category": "Education", "description": "Fellowship support for SC students pursuing M.Phil/Ph.D.", "official_url": "https://scholarships.gov.in/"},
    {"id": "national-fellowship-obc", "name": "National Fellowship for OBC Students", "ministry": "Ministry of Social Justice & Empowerment", "category": "Education", "description": "Fellowship support for OBC students pursuing M.Phil/Ph.D.", "official_url": "https://scholarships.gov.in/"},
    {"id": "pm-yasasvi", "name": "PM YASASVI (Young Achievers Scholarship for Vibrant India)", "ministry": "Ministry of Social Justice & Empowerment", "category": "Education", "description": "Scholarship scheme for OBC, EBC and DNT students at school and college level.", "official_url": "https://scholarships.gov.in/"},
    {"id": "bbbp", "name": "Beti Bachao Beti Padhao (BBBP)", "ministry": "Ministry of Women & Child Development", "category": "Education", "description": "Addresses declining child sex ratio and promotes education and welfare of girls.", "official_url": "https://wcd.nic.in/"},
    {"id": "ssy", "name": "Sukanya Samriddhi Yojana (SSY)", "ministry": "Ministry of Finance", "category": "Education", "description": "Small savings scheme for the girl child, linked with BBBP, offering tax-free returns.", "official_url": "https://www.nsiindia.gov.in/"},
    {"id": "pmkvy", "name": "Pradhan Mantri Kaushal Vikas Yojana (PMKVY)", "ministry": "Ministry of Skill Development & Entrepreneurship", "category": "Skill Development", "description": "Flagship skill-certification scheme offering free short-duration training.", "official_url": "https://www.pmkvyofficial.org/"},
    {"id": "naps", "name": "National Apprenticeship Promotion Scheme (NAPS)", "ministry": "Ministry of Skill Development & Entrepreneurship", "category": "Skill Development", "description": "Reimburses part of apprentice stipend/training cost to employers to promote apprenticeships.", "official_url": "https://www.apprenticeshipindia.gov.in/"},
    {"id": "jss", "name": "Jan Shikshan Sansthan (JSS) Scheme", "ministry": "Ministry of Skill Development & Entrepreneurship", "category": "Skill Development", "description": "Vocational skill training for non-literate, neo-literate and school dropouts, especially in rural areas.", "official_url": "https://dget.gov.in/"},
    {"id": "pm-vidyalaxmi", "name": "PM Vidyalaxmi Scheme", "ministry": "Ministry of Education", "category": "Education", "description": "Facilitates collateral-free education loans for admission to quality higher-education institutions.", "official_url": "https://www.vidyalakshmi.co.in/"},
    {"id": "nai-roshni", "name": "Nai Roshni Scheme", "ministry": "Ministry of Minority Affairs", "category": "Women & Child", "description": "Leadership development training for women belonging to minority communities.", "official_url": "https://minorityaffairs.gov.in/"},
    {"id": "padhna-likhna", "name": "Padhna Likhna Abhiyan", "ministry": "Ministry of Education", "category": "Education", "description": "Adult education scheme to impart functional literacy and numeracy to non-literate adults.", "official_url": "https://education.gov.in/"},
    {"id": "swayam", "name": "SWAYAM (Study Webs of Active Learning for Young Aspiring Minds)", "ministry": "Ministry of Education", "category": "Education", "description": "Free online courses from school to postgraduate level.", "official_url": "https://swayam.gov.in/"},
    {"id": "pm-shri", "name": "PM SHRI Schools Scheme", "ministry": "Ministry of Education", "category": "Education", "description": "Upgrades selected schools nationwide as exemplar schools under the National Education Policy.", "official_url": "https://pmshrischools.education.gov.in/"},
    {"id": "rusa", "name": "Rashtriya Uchchatar Shiksha Abhiyan (RUSA)", "ministry": "Ministry of Education", "category": "Education", "description": "Centrally sponsored scheme to improve access, equity and quality in state higher-education institutions.", "official_url": "https://rusa.nic.in/"},
    {"id": "nose-sc", "name": "National Overseas Scholarship for SC/ST Students", "ministry": "Ministry of Social Justice & Empowerment / Tribal Affairs", "category": "Education", "description": "Financial assistance for SC/ST students pursuing masters/PhD abroad.", "official_url": "https://scholarships.gov.in/"},
    {"id": "ishan-uday", "name": "Ishan Uday Special Scholarship Scheme (NE Region)", "ministry": "Ministry of Education", "category": "Education", "description": "Scholarship for general-degree-level students from the North Eastern Region.", "official_url": "https://scholarships.gov.in/"},

    # ---------------- Housing & Urban / Rural Development ----------------
    {"id": "pmay-g", "name": "PMAY-Gramin (Pradhan Mantri Awas Yojana – Rural)", "ministry": "Ministry of Rural Development", "category": "Housing", "description": "Financial assistance for construction of pucca houses for eligible rural households.", "official_url": "https://pmayg.nic.in/"},
    {"id": "sbm-u", "name": "Swachh Bharat Mission – Urban 2.0", "ministry": "Ministry of Housing & Urban Affairs", "category": "Sanitation", "description": "Sustains open-defecation-free status and improves solid/liquid waste management in cities.", "official_url": "https://sbmurban.org/"},
    {"id": "sbm-g", "name": "Swachh Bharat Mission – Grameen 2.0", "ministry": "Ministry of Jal Shakti", "category": "Sanitation", "description": "Sustains rural sanitation coverage and manages solid/liquid waste in villages.", "official_url": "https://swachhbharatmission.gov.in/"},
    {"id": "amrut2", "name": "AMRUT 2.0 (Atal Mission for Rejuvenation & Urban Transformation)", "ministry": "Ministry of Housing & Urban Affairs", "category": "Urban Development", "description": "Universal coverage of water supply and improves sewerage/septage management in cities.", "official_url": "https://amrut.mohua.gov.in/"},
    {"id": "smart-cities", "name": "Smart Cities Mission", "ministry": "Ministry of Housing & Urban Affairs", "category": "Urban Development", "description": "Area-based development and smart infrastructure across selected cities.", "official_url": "https://smartcities.gov.in/"},
    {"id": "day-nulm", "name": "DAY-NULM (National Urban Livelihoods Mission)", "ministry": "Ministry of Housing & Urban Affairs", "category": "Employment", "description": "Reduces urban poverty by promoting self-employment and skilled wage employment.", "official_url": "https://nulm.gov.in/"},
    {"id": "day-nrlm", "name": "DAY-NRLM (National Rural Livelihoods Mission)", "ministry": "Ministry of Rural Development", "category": "Employment", "description": "Organises rural poor women into self-help groups and supports sustainable livelihoods.", "official_url": "https://aajeevika.gov.in/"},
    {"id": "svamitva", "name": "SVAMITVA Scheme", "ministry": "Ministry of Panchayati Raj", "category": "Rural Development", "description": "Drone-based mapping of rural inhabited land and issue of property/title cards.", "official_url": "https://svamitva.nic.in/"},
    {"id": "jjm", "name": "Jal Jeevan Mission (Har Ghar Jal)", "ministry": "Ministry of Jal Shakti", "category": "Rural Development", "description": "Aims to provide functional household tap water connections to every rural home.", "official_url": "https://jaljeevanmission.gov.in/"},
    {"id": "namami-gange", "name": "Namami Gange Programme", "ministry": "Ministry of Jal Shakti", "category": "Environment", "description": "Integrated conservation mission for rejuvenation of the river Ganga.", "official_url": "https://nmcg.nic.in/"},
    {"id": "atal-bhujal", "name": "Atal Bhujal Yojana", "ministry": "Ministry of Jal Shakti", "category": "Rural Development", "description": "Community-led sustainable groundwater management in water-stressed areas.", "official_url": "https://ataljal.mowr.gov.in/"},
    {"id": "pmgsy", "name": "Pradhan Mantri Gram Sadak Yojana (PMGSY)", "ministry": "Ministry of Rural Development", "category": "Rural Development", "description": "All-weather road connectivity to eligible unconnected rural habitations.", "official_url": "https://pmgsy.nic.in/"},
    {"id": "mgnrega", "name": "Mahatma Gandhi NREGA", "ministry": "Ministry of Rural Development", "category": "Employment", "description": "Legal guarantee of 100 days of wage employment per year to rural households.", "official_url": "https://nrega.nic.in/"},

    # ---------------- Energy ----------------
    {"id": "pm-surya-ghar", "name": "PM Surya Ghar: Muft Bijli Yojana", "ministry": "Ministry of New & Renewable Energy", "category": "Energy", "description": "Subsidised rooftop solar installation for households, targeting free electricity up to a usage threshold.", "official_url": "https://pmsuryaghar.gov.in/"},
    {"id": "ddugjy", "name": "Deendayal Upadhyaya Gram Jyoti Yojana (DDUGJY)", "ministry": "Ministry of Power", "category": "Energy", "description": "Strengthens rural electrification infrastructure and feeder separation.", "official_url": "https://saubhagya.gov.in/"},
    {"id": "pm-kusum", "name": "PM-KUSUM (Kisan Urja Suraksha evam Utthaan Mahabhiyan)", "ministry": "Ministry of New & Renewable Energy", "category": "Energy", "description": "Supports solar pumps and grid-connected solar/renewable power plants for farmers.", "official_url": "https://pmkusum.mnre.gov.in/"},
    {"id": "green-hydrogen", "name": "National Green Hydrogen Mission", "ministry": "Ministry of New & Renewable Energy", "category": "Energy", "description": "Aims to make India a hub for green hydrogen production and export.", "official_url": "https://mnre.gov.in/"},
    {"id": "pm-edrive", "name": "PM E-DRIVE Scheme", "ministry": "Ministry of Heavy Industries", "category": "Energy", "description": "Subsidises electric two/three-wheelers, e-buses and EV charging infrastructure.", "official_url": "https://heavyindustries.gov.in/"},

    # ---------------- Women & Child Development ----------------
    {"id": "icds", "name": "Integrated Child Development Services (ICDS) / Anganwadi Services", "ministry": "Ministry of Women & Child Development", "category": "Women & Child", "description": "Supplementary nutrition, health checkups and pre-school education through Anganwadi centres.", "official_url": "https://wcd.nic.in/"},
    {"id": "pmmvy", "name": "Pradhan Mantri Matru Vandana Yojana (PMMVY)", "ministry": "Ministry of Women & Child Development", "category": "Women & Child", "description": "Cash maternity benefit for pregnant and lactating women for the first living child.", "official_url": "https://pmmvy.wcd.gov.in/"},
    {"id": "mission-shakti", "name": "Mission Shakti", "ministry": "Ministry of Women & Child Development", "category": "Women & Child", "description": "Umbrella mission for safety, security and empowerment of women, including Sambal and Samarthya sub-schemes.", "official_url": "https://wcd.nic.in/"},
    {"id": "one-stop-centre", "name": "One Stop Centre Scheme (Sakhi)", "ministry": "Ministry of Women & Child Development", "category": "Women & Child", "description": "Integrated support (medical, legal, police, counselling) for women affected by violence.", "official_url": "https://wcd.nic.in/"},
    {"id": "ujjawala-anti-trafficking", "name": "Ujjawala Scheme (Anti-Trafficking)", "ministry": "Ministry of Women & Child Development", "category": "Women & Child", "description": "Prevention of trafficking and rescue, rehabilitation and reintegration of victims.", "official_url": "https://wcd.nic.in/"},
    {"id": "working-women-hostel", "name": "Working Women Hostel Scheme", "ministry": "Ministry of Women & Child Development", "category": "Women & Child", "description": "Safe, affordable hostel accommodation for working women, including with their children.", "official_url": "https://wcd.nic.in/"},
    {"id": "mahila-shakti-kendra", "name": "Mahila Shakti Kendra", "ministry": "Ministry of Women & Child Development", "category": "Women & Child", "description": "Community-level engagement to empower rural women through skill and employment linkages.", "official_url": "https://wcd.nic.in/"},

    # ---------------- Social Security, Senior Citizens & Disability ----------------
    {"id": "ignoaps", "name": "Indira Gandhi National Old Age Pension Scheme (IGNOAPS)", "ministry": "Ministry of Rural Development", "category": "Social Security", "description": "Monthly pension for eligible elderly persons below the poverty line, under NSAP.", "official_url": "https://nsap.nic.in/"},
    {"id": "ignwps", "name": "Indira Gandhi National Widow Pension Scheme (IGNWPS)", "ministry": "Ministry of Rural Development", "category": "Social Security", "description": "Monthly pension for eligible below-poverty-line widows, under NSAP.", "official_url": "https://nsap.nic.in/"},
    {"id": "igndps", "name": "Indira Gandhi National Disability Pension Scheme (IGNDPS)", "ministry": "Ministry of Rural Development", "category": "Social Security", "description": "Monthly pension for eligible below-poverty-line persons with severe/multiple disabilities, under NSAP.", "official_url": "https://nsap.nic.in/"},
    {"id": "apy", "name": "Atal Pension Yojana (APY)", "ministry": "Ministry of Finance (PFRDA)", "category": "Social Security", "description": "Guaranteed minimum pension scheme mainly for workers in the unorganised sector.", "official_url": "https://npscra.nsdl.co.in/scheme-details.php"},
    {"id": "pmjjby", "name": "Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY)", "ministry": "Ministry of Finance", "category": "Social Security", "description": "Low-premium annual renewable life insurance cover for bank/post-office account holders.", "official_url": "https://www.jansuraksha.gov.in/"},
    {"id": "pmsby", "name": "Pradhan Mantri Suraksha Bima Yojana (PMSBY)", "ministry": "Ministry of Finance", "category": "Social Security", "description": "Low-premium annual renewable accident insurance cover for bank/post-office account holders.", "official_url": "https://www.jansuraksha.gov.in/"},
    {"id": "pmvvy", "name": "Pradhan Mantri Vaya Vandana Yojana (PMVVY)", "ministry": "Ministry of Finance", "category": "Social Security", "description": "Pension scheme for senior citizens providing an assured guaranteed return, via LIC.", "official_url": "https://licindia.in/"},
    {"id": "rashtriya-vayoshri", "name": "Rashtriya Vayoshri Yojana (RVY)", "ministry": "Ministry of Social Justice & Empowerment", "category": "Social Security", "description": "Provides senior citizens below the poverty line with assisted-living devices (walking sticks, hearing aids, etc.).", "official_url": "https://socialjustice.gov.in/"},
    {"id": "adip", "name": "ADIP Scheme (Assistance to Disabled Persons for Aids/Appliances)", "ministry": "Ministry of Social Justice & Empowerment", "category": "Disability", "description": "Financial assistance for purchase/fitting of durable, sophisticated, scientifically manufactured aids and appliances.", "official_url": "https://socialjustice.gov.in/"},
    {"id": "ddrs", "name": "Deendayal Disabled Rehabilitation Scheme (DDRS)", "ministry": "Ministry of Social Justice & Empowerment", "category": "Disability", "description": "Grants-in-aid to NGOs providing rehabilitation services for persons with disabilities.", "official_url": "https://disabilityaffairs.gov.in/"},
    {"id": "accessible-india", "name": "Accessible India Campaign (Sugamya Bharat Abhiyan)", "ministry": "Ministry of Social Justice & Empowerment", "category": "Disability", "description": "Nationwide flagship campaign for achieving universal accessibility for persons with disabilities.", "official_url": "https://disabilityaffairs.gov.in/"},
    {"id": "national-fellowship-pwd", "name": "National Fellowship for Persons with Disabilities", "ministry": "Ministry of Social Justice & Empowerment", "category": "Disability", "description": "Fellowship support for students with disabilities pursuing M.Phil/Ph.D.", "official_url": "https://scholarships.gov.in/"},

    # ---------------- Employment, MSME & Entrepreneurship ----------------
    {"id": "pmegp", "name": "Pradhan Mantri Employment Generation Programme (PMEGP)", "ministry": "Ministry of MSME", "category": "Self-employment", "description": "Credit-linked subsidy for setting up micro-enterprises to generate self-employment.", "official_url": "https://www.kviconline.gov.in/pmegp/"},
    {"id": "stand-up-india", "name": "Stand-Up India Scheme", "ministry": "Ministry of Finance", "category": "Business", "description": "Bank loans between ₹10 lakh and ₹1 crore for at least one SC/ST and one woman entrepreneur per bank branch.", "official_url": "https://www.standupmitra.in/"},
    {"id": "startup-india-seed", "name": "Startup India Seed Fund Scheme (SISFS)", "ministry": "Ministry of Commerce & Industry", "category": "Business", "description": "Financial assistance to startups for proof of concept, prototype development and market entry.", "official_url": "https://www.startupindia.gov.in/"},
    {"id": "cgtmse", "name": "Credit Guarantee Fund Scheme for Micro & Small Enterprises (CGTMSE)", "ministry": "Ministry of MSME", "category": "Business", "description": "Collateral-free credit guarantee cover for loans to micro and small enterprises.", "official_url": "https://www.cgtmse.in/"},
    {"id": "ncs", "name": "National Career Service (NCS)", "ministry": "Ministry of Labour & Employment", "category": "Employment", "description": "Online portal connecting job seekers, employers, skilling and career-counselling services.", "official_url": "https://www.ncs.gov.in/"},
    {"id": "ddu-gky", "name": "Deen Dayal Upadhyaya Grameen Kaushalya Yojana (DDU-GKY)", "ministry": "Ministry of Rural Development", "category": "Skill Development", "description": "Skilling and placement of rural poor youth.", "official_url": "https://ddugky.gov.in/"},
    {"id": "e-shram", "name": "e-Shram Portal (Unorganised Workers Registration)", "ministry": "Ministry of Labour & Employment", "category": "Employment", "description": "National database of unorganised workers to extend social-security benefits.", "official_url": "https://eshram.gov.in/"},
    {"id": "pli-scheme", "name": "Production Linked Incentive (PLI) Scheme", "ministry": "Various (DPIIT-coordinated)", "category": "Business", "description": "Incentivises incremental manufacturing output across 14 identified sectors.", "official_url": "https://www.pib.gov.in/"},
    {"id": "sfurti", "name": "SFURTI (Fund for Regeneration of Traditional Industries)", "ministry": "Ministry of MSME", "category": "Business", "description": "Organises traditional industries/artisans into clusters for sustainability and scale.", "official_url": "https://sfurti.msme.gov.in/"},
    {"id": "aspire", "name": "ASPIRE Scheme", "ministry": "Ministry of MSME", "category": "Business", "description": "Promotes innovation, rural industry and entrepreneurship through livelihood business incubators.", "official_url": "https://msme.gov.in/"},

    # ---------------- Minority, SC/ST/OBC Welfare ----------------
    {"id": "maulana-azad-fellowship", "name": "Maulana Azad National Fellowship", "ministry": "Ministry of Minority Affairs", "category": "Minority Welfare", "description": "Fellowship for minority-community students pursuing M.Phil/Ph.D.", "official_url": "https://scholarships.gov.in/"},
    {"id": "nai-udaan", "name": "Nai Udaan Scheme", "ministry": "Ministry of Minority Affairs", "category": "Minority Welfare", "description": "Financial support for minority-community candidates clearing UPSC/state civil-service prelims.", "official_url": "https://minorityaffairs.gov.in/"},
    {"id": "seekho-aur-kamao", "name": "Seekho Aur Kamao Scheme", "ministry": "Ministry of Minority Affairs", "category": "Skill Development", "description": "Skill-development programme for minority-community youth to improve employability.", "official_url": "https://minorityaffairs.gov.in/"},
    {"id": "usttad", "name": "USTTAD Scheme", "ministry": "Ministry of Minority Affairs", "category": "Skill Development", "description": "Upgrades traditional arts/crafts skills and preserves heritage among minority artisans.", "official_url": "https://minorityaffairs.gov.in/"},
    {"id": "padho-pardesh", "name": "Padho Pardesh Scheme", "ministry": "Ministry of Minority Affairs", "category": "Education", "description": "Interest subsidy on education loans for minority students pursuing higher studies abroad.", "official_url": "https://minorityaffairs.gov.in/"},
    {"id": "pmjvk", "name": "Pradhan Mantri Jan Vikas Karyakram (PMJVK)", "ministry": "Ministry of Minority Affairs", "category": "Minority Welfare", "description": "Develops socio-economic infrastructure in identified minority-concentration areas.", "official_url": "https://minorityaffairs.gov.in/"},
    {"id": "emrs", "name": "Eklavya Model Residential Schools (EMRS)", "ministry": "Ministry of Tribal Affairs", "category": "Education", "description": "Residential schools providing quality education to Scheduled Tribe students.", "official_url": "https://tribal.nic.in/"},
    {"id": "van-dhan", "name": "Van Dhan Vikas Yojana", "ministry": "Ministry of Tribal Affairs", "category": "Self-employment", "description": "Value-addition and livelihood support for tribal minor-forest-produce gatherers.", "official_url": "https://trifed.tribal.gov.in/"},
    {"id": "pm-adi-adarsh-gram", "name": "Pradhan Mantri Adi Adarsh Gram Yojana (PMAAGY)", "ministry": "Ministry of Tribal Affairs", "category": "Rural Development", "description": "Integrated development of villages with a significant tribal population.", "official_url": "https://tribal.nic.in/"},
    {"id": "pvtg-development", "name": "Development of Particularly Vulnerable Tribal Groups (PVTG) / PM-JANMAN", "ministry": "Ministry of Tribal Affairs", "category": "Rural Development", "description": "Targeted saturation of basic services and livelihood support for Particularly Vulnerable Tribal Groups.", "official_url": "https://tribal.nic.in/"},

    # ---------------- Digital, Infrastructure & Science ----------------
    {"id": "digital-india", "name": "Digital India Programme", "ministry": "Ministry of Electronics & IT", "category": "Digital Infrastructure", "description": "Umbrella programme to transform India into a digitally empowered society and economy.", "official_url": "https://www.digitalindia.gov.in/"},
    {"id": "bharatnet", "name": "BharatNet Programme", "ministry": "Ministry of Communications", "category": "Digital Infrastructure", "description": "Broadband connectivity to gram panchayats and villages across India.", "official_url": "https://bbnl.nic.in/"},
    {"id": "pm-gati-shakti", "name": "PM Gati Shakti National Master Plan", "ministry": "Ministry of Commerce & Industry", "category": "Infrastructure", "description": "Multi-modal connectivity infrastructure planning across ministries for integrated project execution.", "official_url": "https://pmgatishakti.gov.in/"},
    {"id": "make-in-india", "name": "Make in India", "ministry": "Ministry of Commerce & Industry", "category": "Business", "description": "Encourages companies to manufacture in India and boost investment and innovation.", "official_url": "https://www.makeinindia.com/"},
    {"id": "national-broadband-mission", "name": "National Broadband Mission", "ministry": "Ministry of Communications", "category": "Digital Infrastructure", "description": "Ensures broadband access for all and facilitates digital communications infrastructure.", "official_url": "https://dot.gov.in/"},
    {"id": "csc-scheme", "name": "Common Services Centres (CSC) Scheme", "ministry": "Ministry of Electronics & IT", "category": "Digital Infrastructure", "description": "Delivers government and other digital services through village-level access points.", "official_url": "https://csc.gov.in/"},
    {"id": "atal-innovation-mission", "name": "Atal Innovation Mission (AIM)", "ministry": "NITI Aayog", "category": "Skill Development", "description": "Promotes innovation and entrepreneurship, including Atal Tinkering Labs in schools.", "official_url": "https://aim.gov.in/"},
    {"id": "startup-india", "name": "Startup India", "ministry": "Ministry of Commerce & Industry", "category": "Business", "description": "Tax benefits, easier compliance and funding support for recognised startups.", "official_url": "https://www.startupindia.gov.in/"},

    # ---------------- Environment ----------------
    {"id": "ncap", "name": "National Clean Air Programme (NCAP)", "ministry": "Ministry of Environment, Forest & Climate Change", "category": "Environment", "description": "City-level action plans to reduce particulate matter pollution levels.", "official_url": "https://moef.gov.in/"},
    {"id": "national-afforestation", "name": "National Afforestation Programme", "ministry": "Ministry of Environment, Forest & Climate Change", "category": "Environment", "description": "Afforestation of degraded forest land through Joint Forest Management Committees.", "official_url": "https://moef.gov.in/"},
    {"id": "project-tiger", "name": "Project Tiger", "ministry": "Ministry of Environment, Forest & Climate Change", "category": "Environment", "description": "Conservation of tigers in designated tiger reserves across the country.", "official_url": "https://ntca.gov.in/"},
    {"id": "napcc", "name": "National Action Plan on Climate Change (NAPCC)", "ministry": "Ministry of Environment, Forest & Climate Change", "category": "Environment", "description": "Umbrella framework of missions addressing climate-change adaptation and mitigation.", "official_url": "https://moef.gov.in/"},

    # ---------------- Tourism & Culture ----------------
    {"id": "swadesh-darshan", "name": "Swadesh Darshan Scheme", "ministry": "Ministry of Tourism", "category": "Tourism", "description": "Integrated development of theme-based tourist circuits across India.", "official_url": "https://tourism.gov.in/"},
    {"id": "prashad", "name": "PRASHAD Scheme", "ministry": "Ministry of Tourism", "category": "Tourism", "description": "Pilgrimage Rejuvenation and Spirituality Augmentation Drive — develops pilgrimage infrastructure.", "official_url": "https://tourism.gov.in/"},

    # ---------------- Financial Inclusion (additional) ----------------
    {"id": "jansuraksha-umbrella", "name": "Jan Suraksha Schemes (Umbrella: PMJJBY, PMSBY, APY)", "ministry": "Ministry of Finance", "category": "Banking", "description": "Common umbrella branding for the three flagship social-security insurance/pension schemes.", "official_url": "https://www.jansuraksha.gov.in/"},
]


def get_categories():
    return sorted({s["category"] for s in CENTRAL_SCHEMES_CATALOGUE})


def get_catalogue(category: str = ""):
    if not category:
        return CENTRAL_SCHEMES_CATALOGUE
    return [s for s in CENTRAL_SCHEMES_CATALOGUE if s["category"] == category]
